
import flatbuffers

# Generated by `flatc`.
import model.messaging.Message
import model.messaging.Status
from FlatBuffers.model.messaging import Message

# https://flatbuffers.dev/tutorial/#python

if __name__ == "__main__":
    print(1)
